[project]
name = "waar_autonomy"
version = "0.1.0"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "domain",
    "ports",
    "adapters",
    "use_cases",
    "application",
    "infrastructure",
    "infrastructure.env",
    "infrastructure.visualization",
    "experiments",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
