name=KAF_Drone
version=1.0.0
author=Kent Fukuda <kentf@uw.edu>
maintainer=Kent Fukuda <kentf@uw.edu>
sentence=Semi-Autonomous Drone Flight Controller Software for an ESP32 Quadcopter
category=Device Control
url=https://github.com/Washington-Aerial-Robotics/waar-iarc-m10/tree/main/ESP32/KAF_Drone
architectures=esp32
includes=kaf_quadcopter_code.h
